
# This file configures the Supabase CLI used for local development
# and for interacting with your remote Supabase project

# The project ID from your Supabase dashboard
project_id = "hearjlibntcenblbanzz"