
# This file configures the Supabase CLI used for local development
# and for interacting with your remote Supabase project

# The project ID from your Supabase dashboard
project_id = "hearjlibntcenblbanzz"

[api]
# API URL for your project - used for interacting with your project's API
endpoint = "https://hearjlibntcenblbanzz.supabase.co"
# For local development
port = 54321
# Your API anon key
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlYXJqbGlibnRjZW5ibGJhbnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTkzMzIsImV4cCI6MjA1NjY3NTMzMn0.fyTGMrzKOk1Dh49Fw6RJFnhaokZ-syniuabONa1GkdE"

[db]
# Port for local development
port = 54322

[studio]
# Port for local development
port = 54323

[inbucket]
# Port for local development
port = 54324

[storage]
# Port for local development
port = 54325

[functions]
# For local development
serve_port = 54326
